---
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  use-case-1:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKERI: rockylinux:8
            DBTYPE: PG
            DBVERSION: 16
            CLNAME: ro8pg
            EXTRA_VARS: "pgbackrest_excpected_release=2.47 check_pgbackrest_build=true"

    steps:
      - uses: actions/checkout@v3
        with:
          path: check_pgbackrest
      - uses: shogo82148/actions-setup-perl@v1

      - name: Initial step
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/run.sh -i

      - name: Run CI script
        env:
          EDB_REPO_USERNAME: ${{ secrets.EDB_REPO_USERNAME }}
          EDB_REPO_PASSWORD: ${{ secrets.EDB_REPO_PASSWORD }}
          EDB_REPO_TOKEN: ${{ secrets.EDB_REPO_TOKEN }}
          ARCH: use-case-1
          CLPATH: /home/runner/clusters
          CLNAME: ${{ matrix.CLNAME }}
          DBTYPE: ${{ matrix.DBTYPE }}
          DBVERSION: ${{ matrix.DBVERSION }}
          DOCKERI: ${{ matrix.DOCKERI }}
          EXTRA_VARS: ${{ matrix.EXTRA_VARS }}
          RUN_ARGS:
          ACTIVITY: true
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/ci.sh

  use-case-2:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - DOCKERI: ubuntu:20.04
            DBTYPE: PG
            DBVERSION: 16
            CLNAME: u20pg
            EXTRA_VARS: "pgbackrest_excpected_release=2.47 check_pgbackrest_build=true"

    steps:
      - uses: actions/checkout@v3
        with:
          path: check_pgbackrest
      - uses: shogo82148/actions-setup-perl@v1

      - name: Initial step
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/run.sh -i

      - name: Run CI script
        env:
          EDB_REPO_USERNAME: ${{ secrets.EDB_REPO_USERNAME }}
          EDB_REPO_PASSWORD: ${{ secrets.EDB_REPO_PASSWORD }}
          EDB_REPO_TOKEN: ${{ secrets.EDB_REPO_TOKEN }}
          ARCH: use-case-2
          CLPATH: /home/runner/clusters
          CLNAME: ${{ matrix.CLNAME }}
          DBTYPE: ${{ matrix.DBTYPE }}
          DBVERSION: ${{ matrix.DBVERSION }}
          DOCKERI: ${{ matrix.DOCKERI }}
          EXTRA_VARS: ${{ matrix.EXTRA_VARS }}
          RUN_ARGS:
          ACTIVITY: true
        run: cd ${HOME?} && sh ${GITHUB_WORKSPACE?}/check_pgbackrest/tests/ci.sh
